document.addEventListener("DOMContentLoaded", function() {
    
    // 1. Check if we are on a Desktop (Large Screen)
    const isDesktop = window.matchMedia("(min-width: 1025px)").matches;

    if (isDesktop) {
        hijackWhatsAppForDesktop();
    }

    // --- LOGIC: INTERCEPT WHATSAPP CLICK ---
    function hijackWhatsAppForDesktop() {
        // We overwrite window.open ONLY for this session.
        // This effectively "catches" the URL generated by your existing checkout logic
        // without needing to modify the complex validation code in Checkout.html.
        
        const originalOpen = window.open;

        window.open = function(url, target) {
            // Check if the URL is trying to go to WhatsApp
            if (url && (url.includes('wa.me') || url.includes('whatsapp.com'))) {
                // STOP! Show QR Code instead.
                showQRCode(url);
                return null; // Prevent the tab from opening
            } else {
                // If it's a regular link, let it pass normally
                return originalOpen(url, target);
            }
        };
    }

    // --- LOGIC: GENERATE & SHOW QR MODAL ---
    function showQRCode(waUrl) {
        // 1. Create the overlay structure
        const overlay = document.createElement('div');
        overlay.className = 'qr-modal-overlay';
        overlay.style.display = 'flex';
        
        // 2. Use a public QR API to generate the code for the WhatsApp URL
        const qrApiUrl = `https://api.qrserver.com/v1/create-qr-code/?size=250x250&bgcolor=ffffff&data=${encodeURIComponent(waUrl)}`;

        // 3. Populate HTML
        overlay.innerHTML = `
            <div class="qr-card">
                <h3 class="qr-title">Scan to Pay 📱</h3>
                <p class="qr-desc">
                    Since you are on a desktop, simply scan this code with your phone camera to send the order via WhatsApp.
                </p>
                <img src="${qrApiUrl}" class="qr-image" alt="Order QR Code">
                <button class="qr-close-btn">Done, I sent it!</button>
            </div>
        `;

        // 4. Append to body
        document.body.appendChild(overlay);

        // 5. Handle Closing
        const closeBtn = overlay.querySelector('.qr-close-btn');
        closeBtn.onclick = function() {
            overlay.remove();
            // Optional: If you want to trigger the "Order Placed" modal in the background
            // existing logic usually handles this, so we leave it be.
        };

        // Close on background click
        overlay.onclick = function(e) {
            if (e.target === overlay) overlay.remove();
        }
    }
});
